[tool.black]
line-length = 88
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
strict = true

[tool.ruff]
target-version = "py311"
line-length = 88

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"