name: OPA Policy Check

on:
  pull_request:
    paths:
      - 'platform/policy/opa/**'

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: open-policy-agent/setup-opa@v2
      - name: Run OPA tests
        run: |
          opa test platform/policy/opa/policies platform/policy/opa/tests